base_case_2019:
  start_date: 2018-12-31 20:00
  end_date: 2019-01-21 00:00
  time_step: 1h
  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      start_date: 2018-12-31 23:00
      products:
        - duration: 1h
          count: 1
          first_delivery: 1h
      opening_frequency: 1h
      opening_duration: 1h
      volume_unit: MWh
      maximum_volume: 1000000
      price_unit: EUR/MWh
      market_mechanism: pay_as_clear

crm_case_2019:
  start_date: 2018-12-31 20:00
  end_date: 2019-01-21 00:00
  time_step: 1h
  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      start_date: 2018-12-31 23:00
      products:
        - duration: 1h
          count: 1
          first_delivery: 1h
      opening_frequency: 1h
      opening_duration: 1h
      volume_unit: MWh
      maximum_volume: 1000000
      price_unit: EUR/MWh
      market_mechanism: pay_as_clear

    CRM_pos:
      operator: CRM_operator
      product_type: capacity_pos
      start_date: 2019-01-01 01:00
      products:
        - duration: 4h
          count: 1
          first_delivery: 1h
      opening_frequency: 4h
      opening_duration: 1h
      volume_unit: MW
      maximum_volume: 1000000
      price_unit: EUR/MW
      market_mechanism: pay_as_bid

    CRM_neg:
      operator: CRM_operator
      product_type: capacity_pos
      start_date: 2019-01-01 01:00
      products:
        - duration: 4h
          count: 1
          first_delivery: 1h
      opening_frequency: 4h
      opening_duration: 1h
      volume_unit: MW
      maximum_volume: 1000000
      price_unit: EUR/MW
      market_mechanism: pay_as_bid
ltm_case00:
  start_date: 2018-12-31 20:00
  end_date: 2019-01-21 00:00
  time_step: 1h
  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      
      products:
        - duration: 1h
          count: 1
          first_delivery: 1h
      opening_frequency: 1h
      opening_duration: 1h
      volume_unit: MWh
      maximum_volume: 1000000
      price_unit: EUR/MWh
      market_mechanism: pay_as_clear
ltm_case01:
  start_date: 2018-12-31 20:00
  end_date: 2019-01-21 00:00
  time_step: 1h
  bidding_strategy_params:
    scale_firm_power_capacity: 0.1
  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      
      products:
        - duration: 1h
          count: 1
          first_delivery: 1h
      opening_frequency: 1h
      opening_duration: 1h
      volume_unit: MWh
      maximum_volume: 1000000
      price_unit: EUR/MWh
      market_mechanism: pay_as_clear

    # Long Term Market - 7d contracts
    LTM_OTC:
      operator: LTM_operator
      product_type: energy
      start_date: 2018-12-31 22:00
      products:
        - duration: 7d
          count: 1
          first_delivery: 2h
      opening_frequency: 7d
      opening_duration: 1h
      volume_unit: MW
      maximum_volume: 1000000
      price_unit: EUR/MW
      market_mechanism: pay_as_bid
ltm_case02:
  start_date: 2018-12-31 20:00
  end_date: 2019-01-21 00:00
  time_step: 1h
  bidding_strategy_params:
    scale_firm_power_capacity: 0.2
  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      
      products:
        - duration: 1h
          count: 1
          first_delivery: 1h
      opening_frequency: 1h
      opening_duration: 1h
      volume_unit: MWh
      maximum_volume: 1000000
      price_unit: EUR/MWh
      market_mechanism: pay_as_clear

    # Long Term Market - 7d contracts
    LTM_OTC:
      operator: LTM_operator
      product_type: energy
      start_date: 2018-12-31 22:00
      products:
        - duration: 7d
          count: 1
          first_delivery: 2h
      opening_frequency: 7d
      opening_duration: 1h
      volume_unit: MW
      maximum_volume: 1000000
      price_unit: EUR/MW
      market_mechanism: pay_as_bid
ltm_case03:
  start_date: 2018-12-31 20:00
  end_date: 2019-01-21 00:00
  time_step: 1h
  bidding_strategy_params:
    scale_firm_power_capacity: 0.3
  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      
      products:
        - duration: 1h
          count: 1
          first_delivery: 1h
      opening_frequency: 1h
      opening_duration: 1h
      volume_unit: MWh
      maximum_volume: 1000000
      price_unit: EUR/MWh
      market_mechanism: pay_as_clear

    # Long Term Market - 7d contracts
    LTM_OTC:
      operator: LTM_operator
      product_type: energy
      start_date: 2018-12-31 22:00
      products:
        - duration: 7d
          count: 1
          first_delivery: 2h
      opening_frequency: 7d
      opening_duration: 1h
      volume_unit: MW
      maximum_volume: 1000000
      price_unit: EUR/MW
      market_mechanism: pay_as_bid
ltm_case04:
  start_date: 2018-12-31 20:00
  end_date: 2019-01-21 00:00
  time_step: 1h
  bidding_strategy_params:
    scale_firm_power_capacity: 0.4
  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      
      products:
        - duration: 1h
          count: 1
          first_delivery: 1h
      opening_frequency: 1h
      opening_duration: 1h
      volume_unit: MWh
      maximum_volume: 1000000
      price_unit: EUR/MWh
      market_mechanism: pay_as_clear

    # Long Term Market - 7d contracts
    LTM_OTC:
      operator: LTM_operator
      product_type: energy
      start_date: 2018-12-31 22:00
      products:
        - duration: 7d
          count: 1
          first_delivery: 2h
      opening_frequency: 7d
      opening_duration: 1h
      volume_unit: MW
      maximum_volume: 1000000
      price_unit: EUR/MW
      market_mechanism: pay_as_bid
ltm_case05:
  start_date: 2018-12-31 20:00
  end_date: 2019-01-21 00:00
  time_step: 1h
  bidding_strategy_params:
    scale_firm_power_capacity: 0.5
  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      
      products:
        - duration: 1h
          count: 1
          first_delivery: 1h
      opening_frequency: 1h
      opening_duration: 1h
      volume_unit: MWh
      maximum_volume: 1000000
      price_unit: EUR/MWh
      market_mechanism: pay_as_clear

    # Long Term Market - 7d contracts
    LTM_OTC:
      operator: LTM_operator
      product_type: energy
      start_date: 2018-12-31 22:00
      products:
        - duration: 7d
          count: 1
          first_delivery: 2h
      opening_frequency: 7d
      opening_duration: 1h
      volume_unit: MW
      maximum_volume: 1000000
      price_unit: EUR/MW
      market_mechanism: pay_as_bid
ltm_case06:
  start_date: 2018-12-31 20:00
  end_date: 2019-01-21 00:00
  time_step: 1h
  bidding_strategy_params:
    scale_firm_power_capacity: 0.6
  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      start_date: 2018-12-31 23:00
      products:
        - duration: 1h
          count: 1
          first_delivery: 1h
      opening_frequency: 1h
      opening_duration: 1h
      volume_unit: MWh
      maximum_volume: 1000000
      price_unit: EUR/MWh
      market_mechanism: pay_as_clear

    # Long Term Market - 7d contracts
    LTM_OTC:
      operator: LTM_operator
      product_type: energy
      start_date: 2018-12-31 22:00
      products:
        - duration: 7d
          count: 1
          first_delivery: 2h
      opening_frequency: 7d
      opening_duration: 1h
      volume_unit: MW
      maximum_volume: 1000000
      price_unit: EUR/MW
      market_mechanism: pay_as_bid
ltm_case07:
  start_date: 2018-12-31 20:00
  end_date: 2019-01-21 00:00
  time_step: 1h
  bidding_strategy_params:
    scale_firm_power_capacity: 0.7
  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      
      products:
        - duration: 1h
          count: 1
          first_delivery: 1h
      opening_frequency: 1h
      opening_duration: 1h
      volume_unit: MWh
      maximum_volume: 1000000
      price_unit: EUR/MWh
      market_mechanism: pay_as_clear

    # Long Term Market - 7d contracts
    LTM_OTC:
      operator: LTM_operator
      product_type: energy
      start_date: 2018-12-31 22:00
      products:
        - duration: 7d
          count: 1
          first_delivery: 2h
      opening_frequency: 7d
      opening_duration: 1h
      volume_unit: MW
      maximum_volume: 1000000
      price_unit: EUR/MW
      market_mechanism: pay_as_bid
ltm_case08:
  start_date: 2018-12-31 20:00
  end_date: 2019-01-21 00:00
  time_step: 1h
  bidding_strategy_params:
    scale_firm_power_capacity: 0.8
  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      start_date: 2018-12-31 23:00
      products:
        - duration: 1h
          count: 1
          first_delivery: 1h
      opening_frequency: 1h
      opening_duration: 1h
      volume_unit: MWh
      maximum_volume: 1000000
      price_unit: EUR/MWh
      market_mechanism: pay_as_clear

    # Long Term Market - 7d contracts
    LTM_OTC:
      operator: LTM_operator
      product_type: energy
      start_date: 2018-12-31 22:00
      products:
        - duration: 7d
          count: 1
          first_delivery: 2h
      opening_frequency: 7d
      opening_duration: 1h
      volume_unit: MW
      maximum_volume: 1000000
      price_unit: EUR/MW
      market_mechanism: pay_as_bid
ltm_case09:
  start_date: 2018-12-31 20:00
  end_date: 2019-01-21 00:00
  time_step: 1h
  bidding_strategy_params:
    scale_firm_power_capacity: 0.9
  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      start_date: 2018-12-31 23:00
      products:
        - duration: 1h
          count: 1
          first_delivery: 1h
      opening_frequency: 1h
      opening_duration: 1h
      volume_unit: MWh
      maximum_volume: 1000000
      price_unit: EUR/MWh
      market_mechanism: pay_as_clear

    # Long Term Market - 7d contracts
    LTM_OTC:
      operator: LTM_operator
      product_type: energy
      start_date: 2018-12-31 22:00
      products:
        - duration: 7d
          count: 1
          first_delivery: 2h
      opening_frequency: 7d
      opening_duration: 1h
      volume_unit: MW
      maximum_volume: 1000000
      price_unit: EUR/MW
      market_mechanism: pay_as_bid
ltm_case10:
  start_date: 2018-12-31 20:00
  end_date: 2019-01-21 00:00
  time_step: 1h
  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      start_date: 2018-12-31 23:00
      products:
        - duration: 1h
          count: 1
          first_delivery: 1h
      opening_frequency: 1h
      opening_duration: 1h
      volume_unit: MWh
      maximum_volume: 1000000
      price_unit: EUR/MWh
      market_mechanism: pay_as_clear

    # Long Term Market - 7d contracts
    LTM_OTC:
      operator: LTM_operator
      product_type: energy
      start_date: 2018-12-31 22:00
      products:
        - duration: 7d
          count: 1
          first_delivery: 2h
      opening_frequency: 7d
      opening_duration: 1h
      volume_unit: MW
      maximum_volume: 1000000
      price_unit: EUR/MW
      market_mechanism: pay_as_bid
policy_case:
  start_date: 2018-12-31 20:00
  end_date: 2019-01-21 00:00
  time_step: 1h
  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      start_date: 2018-12-31 23:00
      products:
        - duration: 1h
          count: 1
          first_delivery: 1h
      opening_frequency: 1h
      opening_duration: 1h
      volume_unit: MWh
      maximum_volume: 1000000
      price_unit: EUR/MWh
      market_mechanism: pay_as_clear
    # Policy market - contracts for next 7d 
    POL:
      operator: POL_operator
      product_type: energy
      start_date: 2018-12-31 20:00
      additional_fields:
        - contract
        - sender_id
      products:
        - duration: 7d
          count: 5
          first_delivery: 1d
      opening_frequency: 1d
      opening_duration: 1d
      volume_unit: MW
      maximum_volume: 1000000
      price_unit: EUR/MW
      market_mechanism: pay_as_bid_contract
